catalogMode: prefer
minimumReleaseAge: 1
fetchTimeout: 600000
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - playground

allowBuilds:
  esbuild: true
  vue-demi: true

patchedDependencies:
  tab-election@4.6.2: patches/tab-election@4.6.2.patch

catalog:
  '@antfu/eslint-config': ^9.2.0
  '@arethetypeswrong/cli': ^0.18.5
  '@iconify-json/mingcute': ^1.2.8
  '@iconify-json/simple-icons': ^1.2.91
  '@iconify-json/solar': ^1.2.5
  '@moeru/eslint-config': ^0.1.0-beta.20
  '@moeru/std': ^0.1.0-beta.20
  '@playwright/test': ^1.62.1
  '@proj-airi/unocss-preset-chromatic': ^1.1.4
  '@shikijs/markdown-it': ^4.3.1
  '@types/node': ^26.1.2
  '@unocss/eslint-config': ^66.7.5
  '@unocss/reset': ^66.7.5
  '@vitejs/plugin-vue': ^6.0.8
  '@vueuse/core': ^14.3.0
  animejs: ^4.5.0
  es-toolkit: ^1.50.0
  eslint: ^10.8.0
  eslint-plugin-oxlint: ^1.76.0
  jiti: ^2.7.0
  pinia: ^4.0.2
  reka-ui: ^2.10.1
  tab-election: ^4.6.2
  tsdown: ^0.22.14
  typescript: ^6.0.3
  unocss: ^66.7.5
  unplugin-vue-markdown: ^32.0.0
  vite: ^8.2.0
  vue: ^3.5.41
  vue-tsc: ^3.3.9
  bumpp: ^12.2.0
